### ISSUE TITLE
trpc with webpack in prod bundle

### ISSUE THREAD

**Issue by sleaper** [jlalmes/trpc-chrome#10]
Hi guys,
I am using tRPC in my chrome extension. I use webpack for bundling. When I am in dev mode it works perfectly, but when I run production build, I got this error:
(in firefox)
![obrazek](https://user-images.githubusercontent.com/19505081/216791386-29fd4f3f-790c-473f-8afc-511e2fa29670.png)

(in chrome)
![image](https://user-images.githubusercontent.com/19505081/216827711-d1a30494-f1f9-4012-a0c8-28b3b1656a25.png)

In production I need to have files under 4MB for firefox store upload, so I use this setting in webpack:
<img width="262" alt="obrazek" src="https://user-images.githubusercontent.com/19505081/216791432-8bc3ab92-f544-4de8-a8b1-dc0f75b9ae93.png">

I am guessing the error is because of the chunk splitting? Do you have any idea what could be wrong?
If you have any questions feel free to ask!

**Comment by capaj** [comment]
this was totally problem on our end.
What happens with webpack chunks is that the chunked code only really works when included as multiple script tags, but we were only loading the main chunk so it never even ran on bacground page side.
It works awesomely  now that we use a custom index.html for background page generated from webpack.
