### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by jqphu** [jlalmes/trpc-chrome#6]
Hey James!

I know this repo is called trpc-**chrome** but any thoughts on adding firefox support?

Seems like we only need:
* runtime.port
* runtime.onConnect.addListener

I think it should be simple to just use something like https://github.com/mozilla/webextension-polyfill but since theres few functions we could also do it manually by detecting whether it is chrome or firefox.

The more annoying part is probably renaming everything.

Either way thanks for creating this :D

**Comment by asix1337** [comment]
@jqphu Firefox supports both the chrome and browser namespaces.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities?retiredLocale=de#firefox_supports_both_the_chrome_and_browser_namespaces

**Comment by jqphu** [comment]
Oh amazing!

I'll close this and try it out then :).

Thanks!
